services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-api:
    build:
      context: .                      # <-- solution kökü
      dockerfile: ./Config.Api/Dockerfile
    environment:
      - Mongo__ConnectionString=mongodb://mongo:27017
    ports: ["5080:8080"]
    depends_on:
      mongo:
        condition: service_healthy

  admin-mvc:
    build:
      context: .                      # <-- solution kökü
      dockerfile: ./Admin.Mvc/Dockerfile
    environment:
      - Api__BaseUrl=http://config-api:8080
    ports: ["5070:8080"]
    depends_on: [ config-api ]

volumes:
  mongo-data:
